### ISSUE TITLE
Target user not found !

### ISSUE THREAD

**Issue by eusuntpopa** [88um/instagram-report-bot#1]
I receive this error: 
"Target user not found !"

I tried different proxies, different accounts... 
![InkedScreenshot 2022-01-22 011129_LI](https://user-images.githubusercontent.com/98192945/150611854-766f6218-8a33-4dcf-9608-4d768747bcd4.jpg)

**Comment by 88um** [comment]
> I receive this error: "Target user not found !"
> 
> I tried different proxies, different accounts... ![InkedScreenshot 2022-01-22 011129_LI](https://user-images.githubusercontent.com/98192945/150611854-766f6218-8a33-4dcf-9608-4d768747bcd4.jpg)

Does it work in no proxy mode? If it does, then its a proxy error, if not then try checking to make sure the account reporting is fine. If all fails, I added a new main.exe

**Comment by eusuntpopa** [comment]
is working now. but what is this? i receive this after 10-15 reports. 
![Screenshot 2022-01-22 222338](https://user-images.githubusercontent.com/98192945/150654299-eb8e1fc6-7aca-4830-be34-87368c4b5ab4.png)

**Comment by 88um** [comment]
> is working now. but what is this? i receive this after 10-15 reports. ![Screenshot 2022-01-22 222338](https://user-images.githubusercontent.com/98192945/150654299-eb8e1fc6-7aca-4830-be34-87368c4b5ab4.png)

Thats a redirect exception, could be due to the proxy(s), I'll make sure to handle that in the future.
