### ISSUE TITLE
only reporting once

### ISSUE THREAD

**Issue by jazxminemasters** [88um/instagram-report-bot#2]
everything seems to work fine at first its actually the first bot that i used that actually even reports anything but it only reports once no matter how many reports i request and i checked my reports it only reports once, maybe update ? idk

**Comment by 88um** [comment]
> everything seems to work fine at first its actually the first bot that i used that actually even reports anything but it only reports once no matter how many reports i request and i checked my reports it only reports once, maybe update ? idk

Thats how their API works, I can not change that unfortunately. But yes, I do understand what you mean, it will (mostly) only show your recent report. Mostly because sometimes it can show two separate report options (i.e. one for self and one for hate).
